### ISSUE TITLE
Feature request: Add other number formats and languages

### ISSUE THREAD

**Issue by Ahmed-mo-rizk** [gtg922r/obsidian-numerals#11]
im using arabic in this case

![image](https://user-images.githubusercontent.com/97184300/202151530-dbd0ba07-55ba-4284-875f-ac1f3fbe0f99.png)

![image](https://user-images.githubusercontent.com/97184300/202151561-76ef5fb5-7879-4282-a17c-c83e052eaa88.png)

**Comment by gtg922r** [comment]
Acknowledged. Unfortunately this would be heavily dependent on support from mathjs and I don't have the resources to implement myself. 

If there is a math library that handles Arabic I'm happy to look into offering multiple math engines. However a cursor search didn't turn up anything.

Marking as wontfix as a math engine re-write isn't within the scope of this plugin.
