### ISSUE TITLE
[feature request] Add autocompletion for functions and variables inside code block

### ISSUE THREAD

**Issue by gtg922r** [gtg922r/obsidian-numerals#15]
Users should be able to have autocomplete of Numerals functions and variables when inside a code block. This could be provided through either native Numerals support, or by adding the appropriate word list to another plugin (for example [tth05/obsidian-completr: Auto-completion plugin for the obsidian editor.](https://github.com/tth05/obsidian-completr))

**Comment by gtg922r** [comment]
Initial implementation done. Need to complete some testing

**Comment by gtg922r** [comment]
Autocompletion is available in 1.0.8, which can be tested with BRAT. 

Currently it's crash on mobile which is delaying roll-out

**Comment by Archie-2021** [comment]
> Users should be able to have autocomplete of Numerals functions and variables when inside a code block. This could be provided through either native Numerals support, or by adding the appropriate word list to another plugin (for example [tth05/obsidian-completr: Auto-completion plugin for the obsidian editor.](https://github.com/tth05/obsidian-completr))

It is good idea , but I just installed latex-suite and snippets and auto-completion in that works very well, If this plugin use exact latex syntax (without dropping `\`) and Numerals Plugins gets activated in math code blocks it would be awesome and there would be no need for reinventing those features again.

**Comment by mayurankv** [comment]
Really agree with Archie, that would be a brilliant workflow!

**Comment by gtg922r** [comment]
Autocompletion included and launched in *Numerals* 1.2
