### ISSUE TITLE
Have $ without currency?

### ISSUE THREAD

**Issue by jamie9090** [gtg922r/obsidian-numerals#17]
Hey there - love this.

Would appreciate being able to disable the conversion from "$" to USD in calculations

Or to have support for a different default currency

From my end, I use AUD :)

**Comment by gtg922r** [comment]
Yeah this is definitely on the roadmap, I'll try to do this next. 

Currently, the underlying library necessitates a conversion to something other than the `$` symbol so my plan is simply to allow users to define what the currency associated with `$` is.

**Comment by jamie9090** [comment]
Awesome, thanks so much!

**Comment by gtg922r** [comment]
Initial support added and ready for testing. Should be able to release by end of week. Will be able to select all ISO currencies that use `$`, include USD, AUD, CAD, NZD, MXN, etc

![Screenshot 2022-12-13 at 1 54 31 AM](https://user-images.githubusercontent.com/1195174/207285969-a4bc5bbe-3535-42c4-a72d-0ee771a1acaf.png)

Note, for technical reasons within the mathjs math engine that *Numerals* uses, I can't allow use of `$<amount>` without mapping it to a currency. I'm essentially creating a new physical unit, and the convention for units is they trail the number they apply to (e.g. `4km` or `10 seconds`).
