### ISSUE TITLE
[Feature Request] Way to easily sum a group of variables

### ISSUE THREAD

**Issue by Jack-Chronicle** [gtg922r/obsidian-numerals#18]
Started using this recently, but noticed if you have a group of variables you have to name them each to sum them together, and aren't able to just request whatever heading they're under to sum them or sum from Variable A to Variable X and everything between them

I may be missing something that allows you to do this, but if not it would be great to add it

**Comment by gtg922r** [comment]
There is currently no way to do this, though I certainly understand the use case and have had the same issue. 

Let me think of a reasonable syntax for such a thing.

**Comment by ChristinWhite** [comment]
I think Calca’s syntax is a reasonable approach to this problem:

![F4016B34-A455-432D-902B-35E2798D44A0](https://user-images.githubusercontent.com/1746405/211179752-0b54947c-a0d4-47a6-a193-a43e9f8408d1.jpeg)

It works quite well for some uses. 

On the other hand, there are times when I really just want a quick running tally and would prefer to do away with assigning variables altogether and have some kind of Soulver mode where you add basic arithmetic and values and treat any text as a comment, then return the total at the end of the statement. Maybe a `sum` code block.

**Comment by Jack-Chronicle** [comment]
I think a way to incorporate this into the plug-in could be using indent levels?

The first level would be the sum total of those indented below it, similar to how the Sigma plug-in works

**Comment by ChristinWhite** [comment]
I've been playing with Numbr quite a bit and I really like it's syntax, definitely more so than Calca's:

```
# List of items

Item one:    256
Item two:   -512
Item three: 1024

List Variable = sum 
```

Basically, `sum` just grabs everything above it up to the most recent heading.

Unfortunately, I'm getting constant data loss with Numbr so I'm still back to searching for something dependable I can run on iOS until Numerals adds support for summing.

**Comment by gtg922r** [comment]
I've found a rather straight-forward way to implement this.  And have the initial implementation done. 

The syntax I am leaning towards is `@sum` or `@total` (its case-insensitive so capitalize however you like).

I would have liked to use `sum` or `total` to be similar to other apps, but someone may already have notes with `total = blah + blah` and I don't want to cause confusion there. There are other places I am using `@` as a Numerals-specific directive, so I'm going to stick with that to force the user to be specific when doing a sum/total. 

Thoughts on this syntax from folks?

![image](https://github.com/gtg922r/obsidian-numerals/assets/1195174/03ca131e-0689-413e-89b4-cd68cd01406d)

**Comment by ChristinWhite** [comment]
Looks fantastic to me!

**Comment by Jack-Chronicle** [comment]
That looks great!

**Comment by gtg922r** [comment]
This is now live in [Numerals 1.4 (Beta)](https://github.com/gtg922r/obsidian-numerals/releases/tag/1.4.0)

Would really appreciate beta testing and feedback prior to me pushing this out as a full release! Please see the instructions on the README for how to use BRAT to beta test!

**Comment by Stakker** [comment]
Looks like it's working, cheers! 🙏

**Comment by gtg922r** [comment]
Closing with public release of [Numerals 1.5](https://github.com/gtg922r/obsidian-numerals/releases/tag/1.5.0)
