### ISSUE TITLE
Decimal separator

### ISSUE THREAD

**Issue by yakovlev-i-a** [gtg922r/obsidian-numerals#19]
Thank you for useful plugin! In my computer with Windows 10 I set **Decimal Symbol** to dot in **Regional and Language Options**. However, in the rendered view I still see commas. It would be nice to define the decimal symbol in **Plugin Settings** explicitly as a suggestion.

![image](https://user-images.githubusercontent.com/121093094/208636874-0aac6569-b5ca-489a-bcf0-191b0a8292b4.png)

**Comment by gtg922r** [comment]
@yakovlev-i-a just to confirm you are talking about in the rendered results, correct? 

I use a javascript function `toLocaleString()`that should account for your language and locale and deduce the correct format.

Would you mind sharing your current `locale` by opening up the console in obsidian (`alt`-`ctrl`/`cmd`-`i`), and typing `navigator.language`. 

If possible I'd like for this to be auto-detected and not have to add another setting. Though if its necessary I will.

**Comment by yakovlev-i-a** [comment]
Thank you for your comment. I see the value `ru` in the console. Within this locale, a comma is used as a decimal separator indeed. But I would prefer to change it to a dot. As I reported, changing the parameter in **Regional and Language Options** in Windows settings does not help, as well as language changing to **English** in the Obsidian setting. Probably, I should change my locale somewhere else, but I don't know. For example, Excel has the option to use a system separator or directly defined symbols (as in the screenshot below). A similar option in the plugin settings would be helpful to someone who wants to see the separator symbol different from the locale settings.
![image](https://user-images.githubusercontent.com/121093094/208868770-a459ce9a-b217-4d29-b3ae-d07bd9c74703.png)

**Comment by gtg922r** [comment]
Adding the ability to specify the locale directly, which should fix your issue.

**Comment by gtg922r** [comment]
The new 1.2 release gives you the option to choose your number formatting option. Update to the latest version of *Numerals*, open *Numerals* settings, and scroll down to `Rendered Number Format`. The default is your system setting, but you can the format you'd like to force *Numerals* to use.
