### ISSUE TITLE
awesome plugin! please add fraction support

### ISSUE THREAD

**Issue by KraXen72** [gtg922r/obsidian-numerals#2]
i would love if i could do calculations with fractions.
currently i have to use latex and latex2sympy2, which is nonideal as writing latex is somewhat cumbersome

**Comment by gtg922r** [comment]
Fractions are supported via the `fraction` function. 
```
fraction(1/3) + fraction(1/4) → 7/12
```
For further information on functions that support fractions, see [math.js | Fractions](https://mathjs.org/docs/datatypes/fractions.html)

Is there additional support you'd like to see here?

**Comment by claremacrae** [comment]
Think I would suggest closing this now, since its documented now on the README how to use fractions.

**Comment by gtg922r** [comment]
Closing as fractions function exists and is now documented (thanks @claremacrae). Feel free to re-open if there is a specific feature you want to see supported. 

Likely numerals will not support symbolic math by default (hence the `fraction` function) as its primary use is as a numeric calculator. You might want to consider [Obsidian Mathpad](https://github.com/Canna71/obsidian-mathpad) if you are looking for symbolic math as I believe that may support it natively. 

Additionally if you just want to see fractions rendered as fractions, then keep an eye on #7 , which will render them in the input as fractions

**Comment by gtg922r** [comment]
Note that with release 0.0.12, TeX rendering of inputs and results has been implemented either by setting the default render style in settings, or by using `math-tex`. This will render fractions in a more "fraction-like" format - though you will still need to use `fraction()` if you want to force the calculation to not result to a number. 

![Screenshot 2022-11-13 at 1 47 28 AM](https://user-images.githubusercontent.com/1195174/201515774-aae44b67-5803-435f-a7df-aa4124eaf896.png)

**Comment by KraXen72** [comment]
very nice! maybe it could be useful to hide the `fraction()` text from the rendered result? it's already pretty useful. (as an option/default ig)
you could differentiate the 2 styles by using \tfrac for the number resulting ones and \dfrac (tall) for `fraction()`
