### ISSUE TITLE
No update received

### ISSUE THREAD

**Issue by RobertoHRO** [gtg922r/obsidian-numerals#26]
Somehow I don't receive the update for 1.0.8:

![image](https://user-images.githubusercontent.com/25647024/213993557-42cff71c-90c1-4382-a844-95a41a9cbc0b.png)

**Comment by gtg922r** [comment]
1.0.8 is a beta release. To update to it, follow the instructions for installing via BRAT in the README. 

Apologies, I should've made that more clear. 

The non-beta release should be out by the end of this week.

**Comment by gtg922r** [comment]
The beta release is still crashing on mobile, so having to figure that out before its released to prod.

**Comment by gtg922r** [comment]
@RobertoHRO are you using BRAT? There is a new beta release which BRAT should pick-up: 1.0.9.

**Comment by RobertoHRO** [comment]
Now I am using BRAT. And this is wat I got:
![grafik](https://user-images.githubusercontent.com/25647024/216770893-04a85aa3-5e29-4856-bf3a-7477444afc04.png)
And it has the autocompletion - I think its working! - Thank you.

And once again: Your Plugin is super helpful! - Thank you very much! - More and more colleagues are using it!
