### ISSUE TITLE
This is incredible!

### ISSUE THREAD

**Issue by Bobronium** [gtg922r/obsidian-numerals#30]
No particular issue here, I just want to say that I'm grateful for this plugin.  Thank you, @gtg922r.

I never was good at 'math' in school, but got quite proficient at programming, and I was looking for something that would help me transfer my programming skills to writing math equations and calculations.

The key element that makes this 100 time simpler to learn than handwritten math is interactivity, and the fact that it stays in Obsidian allows for easy persistence and integration with my current habits.

This is really important piece of software.

Please, consider setting up a link to donations. 

I rarely donate to anyone, but this plugin helped me to make a really important and personal discovery: math is an instrument, and it's easy to learn it while using it to solve real problems.

**Comment by gtg922r** [comment]
Thank you for the kind words! None of this would be possible without Obsidian or [mathjs](https://mathjs.org/), so if you're feeling generous please support them!
