### ISSUE TITLE
Numbers over 1000 in math-tex

### ISSUE THREAD

**Issue by Kaporos** [gtg922r/obsidian-numerals#32]
Hey there ! 
I have an issue when using **math-tex**, numbers over 1000 don't show up !

I'm using current block:

```math-tex
a = 1000
```

![image](https://user-images.githubusercontent.com/34960023/222371654-f5599f43-d9d1-4745-abd2-4d7125ce800a.png)

(And another minor problem, letters with indices dont show up correctly either)

```math-tex
q_0 = 5
```
![image](https://user-images.githubusercontent.com/34960023/222373693-86e8be34-6fdd-4fd3-808f-0bc9f811d44e.png)

But the optimal would be 

![image](https://user-images.githubusercontent.com/34960023/222373754-909bc3e4-9432-46c3-b1ad-22625bd6f70c.png)
(rendered with $q_0 = 5$)

Anyway, thank you for this plugin, its sooo useful :)

Have a great day !

**Comment by gtg922r** [comment]
The first issue is captured in #23. I know the bug, just trying to work out what the desired outcome should be. 

Would you mind filing a second feature request for the second one? Might be tricky but can certainly look in to it

**Comment by Kaporos** [comment]
Hey !

I made a PR for the second one, so you can see easily what i meant !

https://github.com/gtg922r/obsidian-numerals/pull/33

And for the first one, it appeared than when i'm using this repo code built by myself, the problem isnt there anymore.. i don't know why !

**Comment by gtg922r** [comment]
I fixed the issue you were seeing but I haven't pushed the release yet. So if you built from source it's fixed, but in the version from the Obsidian store it still has the bug.
