### ISSUE TITLE
[Feature Request] Add feature to calculate total 

### ISSUE THREAD

**Issue by nazarhussain** [gtg922r/obsidian-numerals#36]
I had been using this plugin in Obsidian to primarily replace my usage of `Numi` app. It would be really nice if you can add a feature like `TOTAL` function in `Numi` which actually sum up all the evaluations above. 

```
Coffe: 2,4 -> 2,4
Bread: 2,8 -> 2,8
= TOTAL -> 5,2
```

This will be so helpful and hope it's easy to implement.

**Comment by jemgold** [comment]
yes! would love this

**Comment by ChristinWhite** [comment]
I believe this is a duplicate of #18, there’s some discussion about syntax there so additional feedback might be useful.

**Comment by Stakker** [comment]
I'm also missing this feature very much, but I wrote my comment in the duplicate issue mentioned above :-)

**Comment by gtg922r** [comment]
This is now live in [Numerals 1.4 (Beta)](https://github.com/gtg922r/obsidian-numerals/releases/tag/1.4.0)

Would really appreciate beta testing and feedback prior to me pushing this out as a full release! Please see the instructions on the README for how to use BRAT to beta test!

**Comment by nazarhussain** [comment]
> This is now live in [Numerals 1.4 (Beta)](https://github.com/gtg922r/obsidian-numerals/releases/tag/1.4.0)

That works like a charm!

**Comment by gtg922r** [comment]
Closing with public release of [Numerals 1.5](https://github.com/gtg922r/obsidian-numerals/releases/tag/1.5.0)

**Comment by vaygr** [comment]
@gtg922r I think it would be nice to have an option to display total regardless of blank lines / comments. Do you think it's feasible to implement?
