### ISSUE TITLE
Subscript support

### ISSUE THREAD

**Issue by Alex-Guendel** [gtg922r/obsidian-numerals#37]
Hi, perhaps I just haven't figured it out but I've not been able to make subscripts work. In latex this is done most easily with an underscore - in numerals that renders as eg t_i for TEX mode. Feel like its a minor quibble for an overall fantastic app!

**Comment by Aeases** [comment]
I'm having the same 'issue', defiently need this before I can really use numerals personally, looks cool as from the pictures tho

**Comment by gtg922r** [comment]
This has been one of the top feature requests. I'll prioritize it for development

**Comment by gtg922r** [comment]
Initial development done. Should have a bets out soon

**Comment by Alex-Guendel** [comment]
Woohoo thanks!

**Comment by gtg922r** [comment]
Forgot to mention this should be working in -tex mode with beta starting at 1.3.0. See the README for instructions on how to get the beta with BRAT. 

```
'''math-tex
speed_car = 200 mi / hr    
time_accel = 1000 s 
x_car = time_accel * speed_car
'''
```

![image](https://github.com/gtg922r/obsidian-numerals/assets/1195174/d48c6ab1-e659-46fa-8580-be600430d6ee)

**Comment by Alex-Guendel** [comment]
You went above and beyond my friend, thanks!
