### ISSUE TITLE
in Android, the result is displayed in 2 lines: 1 for the arrow, 1 for the number.  : \

### ISSUE THREAD

**Issue by libweirdness** [gtg922r/obsidian-numerals#38]
I'm in Android 11, & told it to show my results in Engineering notation, because small values disappeared in the conventional/default rendition setting...

Since then, it's been usually taking 2 lines to display the result, with the 1st line containing *only* an arrow.

This wastes screen-real-estate, & makes it much harder to parse a column of answers, for me.

Please give the result enough column-width to display its text in a single line.

---

Thank you for making this, btw!

More capable than Sigma, fersure, & very much appreciated!

Salut, Namaste, & Kaizen, eh?

( :

**Comment by gtg922r** [comment]
Would you mind adding some examples with the raw text and screenshots?
Thanks!

**Comment by gtg922r** [comment]
Going to close this for now. Feel free to re-open if its still a problem
