### ISSUE TITLE
Wrong units in result (W / m^2 => m^-4)

### ISSUE THREAD

**Issue by kobayashison** [gtg922r/obsidian-numerals#41]
Here an example:
```
potenza_pannello = 410 W → 410 W
area_pannello = 2 m * 3 m → 6 m^2
densità_potenza = potenza_pannello / area_pannello W/m^2 → 68,333 m^-4
```

**Comment by gtg922r** [comment]
I think this is an order of operations issue. 

Try:
```
densità_potenza = (potenza_pannello / area_pannello) in W/m^2
```
or 
```
densità_potenza = potenza_pannello / area_pannello in W/m^2
```

Closing, but please re-open if its still an issue

**Comment by kobayashison** [comment]
My mistake was the lack of "in" keyword, not a problem of order, so it works also like the second suggestion you wrote, without parenthesis. Thank you!
