### ISSUE TITLE
Issue with math-tex and decimals

### ISSUE THREAD

**Issue by MalysMarcin** [gtg922r/obsidian-numerals#45]
Hi,
Numerals is great, but in math-tex style it does not calculate results with comma.
If I calculate:
1/2*(75 kg+1.8 kg)*(0.2 m)^2
I get
=1,536 kg m^2 - which is correct
However, in tex style I get:
1536 kg m2 - so without comma.

I checked all options of decimal separator and changed also system settings for decimal symbol.

It is windows based system.
Where could be a problem? On Your readme file I can see tex style with decimal so it should work?
Reagrds
Marcin
![image](https://user-images.githubusercontent.com/123721968/235412556-da2fe6d1-608e-4911-9370-d249e3692a7a.png)

**Comment by gtg922r** [comment]
@MalysMarcin thanks for highlighting. I had hoped release [1.2.0](https://github.com/gtg922r/obsidian-numerals/releases/tag/1.2.0) fixed these bugs!

- Can you please check what version of Obsidian you are currently running?
- If you are running > 1.2.0, can you please open the console (`Cmd`/`Ctrl`-`alt`-`I`), find the console tab, and type in `navigator.language`, and share the results?

**Comment by MalysMarcin** [comment]
It looks like version 1.1.16 but cannot get 1.2.0 from Obsidian web page.
Please find screen pic below:
![image](https://user-images.githubusercontent.com/123721968/235581950-6a72a093-ee1c-4f9a-8a12-4330843ac34e.png)

**Comment by MalysMarcin** [comment]
Hi,
I realized today that your ask was not for Obsidian version but for Numeral version.
In that case I am using 1.2.0
![image](https://user-images.githubusercontent.com/123721968/235832440-a6a21fec-f63e-49eb-979d-41f7c70a8edb.png)
:)

**Comment by gtg922r** [comment]
Finally found the bug! I think it should be fixed now. Its in the latest Numerals beta, 1.3.1. To install the beta, please see the [beta instructions in the README](https://github.com/gtg922r/obsidian-numerals#using-brat) to install via BRAT. 

If you find this bug is still an issue with the beta, please re-open it!
