### ISSUE TITLE
Modify for NotePlan?

### ISSUE THREAD

**Issue by ebergmundur** [gtg922r/obsidian-numerals#51]
Hi, this is a great asset to Obsidian, it might also be quite useful in [NotePlan](https://noteplan.co) a Markup based planning application.

all the best 

Einar

**Comment by gtg922r** [comment]
I don't use NotePlan, so unfortunately I'm not planning on developing plugins for it. 

However, it does look like there is already a plugin that is similar and uses mathjs (like Numerals) to provide a similar functionality: [plugins/dwertheimer.MathSolver · NotePlan/plugins](https://github.com/NotePlan/plugins/tree/main/dwertheimer.MathSolver)
