### ISSUE TITLE
Currency CHF not supported

### ISSUE THREAD

**Issue by jowitte** [gtg922r/obsidian-numerals#52]
Minor issue. I tried "CHF" as a currency symbol for Swiss francs, but it's not supported. Is there a workaround?

**Comment by trippleflux** [comment]
Also please add "IDR" for Indonesian Rupiahs.

**Comment by gtg922r** [comment]
#54 created to support custom currencies rather than just a preset list which is how I'll handle additional currency types.

**Comment by gtg922r** [comment]
Marking as dupe of #54
