### ISSUE TITLE
Numerals TeX rendering style outputs wrong results or no results at all

### ISSUE THREAD

**Issue by Peterf1982** [gtg922r/obsidian-numerals#60]
There seems to be a bug within the TeX rendering of the Numerals plugin:

The following code outputs correct numbers:
~~~
```math
lambda=780.246021 nanometer
nu=speedOfLight/lambda
```
~~~

The same code in math-tex environment
~~~
```math-tex
lambda=780.246021 nanometer
nu=speedOfLight/lambda
```
~~~

outputs a wrong result for lambda (wrong order of magnitude) and no result for nu at all.
See picture below
![Bug_Numerals_Tex_annotation](https://github.com/gtg922r/obsidian-numerals/assets/144056705/6c626a39-8fdc-4854-9db8-adad685873e2)

Numerals: 1.2.0
Obsidian: v1.4.5

**Comment by gtg922r** [comment]
Very odd. Can you please share your locale? (E.g. what country and language
is your system set to?) Many of these types of issues have been due to bugs
in the number format conversions based on locale.

**Comment by Peterf1982** [comment]
Windows 10 language German(Germany), country Germany.
I also attached the settings for decimal separator, etc.
![Locale](https://github.com/gtg922r/obsidian-numerals/assets/144056705/e01f1188-71ee-4960-9ee8-58460b9aefb4)

Thanks for having a look at it!

**Comment by gtg922r** [comment]
Finally found the bug! I think it should be fixed now. Its in the latest Numerals beta, 1.3.1. To install the beta, please see the [beta instructions in the README](https://github.com/gtg922r/obsidian-numerals#using-brat) to install via BRAT. 

If you find this bug is still an issue with the beta, please re-open it!
