### ISSUE TITLE
Enhancement Suggestion: Render code while editing in live preview

### ISSUE THREAD

**Issue by BananenRitter** [gtg922r/obsidian-numerals#73]
Shows graphically rendered code while editing:
1. Renders the currently active line...
2. Renders +n lines above/ below the currently active line...
...in source mode

- Only renders lines without major syntax error that prevents from rendering
- n Value can be changed between 0-10, Standard is 1

**Comment by gtg922r** [comment]
Unfortunately this would be extremely difficult and is outside the scope of this plugin. 

Obsidian allows plugins to register to handle the rendering of code blocks - but it only does this on full code blocks, and when the cursor is not inside a code block. To support this feature I think I'd have to tie into renderer itself and do my own processing which is just too much heavily lifting. 

If I'm missing something and this is more straightforward than I realize feel free to re-open
