### ISSUE TITLE
Units conversion behaving weirdly

### ISSUE THREAD

**Issue by VictorJermiin** [gtg922r/obsidian-numerals#76]
Is there a way I can force obsidian numerals to convert the units in the right way. In the example image it has the right units but it does not reduce the units to J K^-1 (Joules per Kelvin). I have had a lot of similar problems like this with the units.
![image](https://github.com/gtg922r/obsidian-numerals/assets/45830483/7470b6df-9d92-4b7f-b16b-b8a941f6fe9c)

**Comment by gtg922r** [comment]
@VictorJermiin - yes you can force the units you want: just follow any calculation with "in..."

for example:
```
``'math
delta_S = C_V * log (T_f / T_i) in J K^-1
``'
```
works:

![image](https://github.com/gtg922r/obsidian-numerals/assets/1195174/0f9e0890-45b0-4c3f-98a0-ed17ef52d196)

**Comment by gtg922r** [comment]
note: "to" also works:
```
``'math
100 km/hr in mi/hr
100 km/hr to mi/hr
``'
```
